# Generated by Django 6.0.5 on 2026-05-13 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestamos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['estado'], name='prestamos_p_estado_ca1dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['fecha_prestamo'], name='prestamos_p_fecha_p_fa8bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['fecha_devolucion'], name='prestamos_p_fecha_d_107790_idx'),
        ),
    ]
