# Generated by Django 6.0.5 on 2026-05-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='notificacio_estado_1d9c95_idx',
            old_name='notificacio_estado_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='notificacio_usuario_c5ce45_idx',
            old_name='notificacio_usuario_fecha_idx',
        ),
    ]
