# Generated by Django 6.0.5 on 2026-05-14 04:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0003_alter_categoria_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_devolucion', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DEVUELTO', 'Devuelto'), ('RETRASADO', 'Retrasado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='libros.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'préstamo',
                'verbose_name_plural': 'préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
